### PR TITLE
Improved sidebar

### PR DESCRIPTION
**Pull request by richyk1**

### CODE REVIEW

**Comment by Felix-Thornblad** [comment]
There is a bug where all projects are displayed as Github projects

**Review by Kax-y — COMMENTED** [review]
image
Could you make it update if you type the same name (instead of creating duplicates)?
Also, could you give Jira two fields. One for "Project Key" and one for "Domain Name"?
(I'm not 100% this should be done for this PR so correct me if I'm wrong)

**Comment by Felix-Thornblad** [comment]
Yeah, that is on my todo list, this fix was just to get back stuff that were lost in the update

**Comment by Kax-y** [comment]
> Yeah, that is on my todo list, this fix was just to get back stuff that were lost in the update

Alright, great!

**Review by Kax-y — APPROVED** [review]

**Pull request merged**
